name: Verify and Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: ["3.12"]
        poetry-version: ["1.8"]

    steps:  
    - name: checkout branch commit
      uses: actions/checkout@v4

    - name: 'Set up Python (cache: pip)'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version}}
        cache: 'pip'

    - name: Initial Configs and Install Poetry
      run: |
        pip install poetry==${{ matrix.poetry-version}}
        git config --local core.hooksPath .githooks/
        chmod +x .githooks/pre-commit .githooks/pre-push
    
    - name: Set up Poetry Cache
      uses: actions/setup-python@v5
      with:
        cache: 'poetry'

    - name: Install packages
      run: python scripts/install_packages.py
      continue-on-error: false   

    - name: Test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        cd server
        poetry run pytest -v

    - name: test log artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testresults_tap
        path: server/testresults.tap
    
        